# Etapa 1: criar pasta e colocar arquivo de dependencia nele, também baixar elas e buildar.
FROM node:22-alpine3.18 AS build

WORKDIR /app

COPY package.json pnpm-lock.yaml tsconfig.json ./
RUN npm install -g pnpm
RUN pnpm install

COPY src ./src

RUN npm run build

# Etapa 2: baixar dependenc. de prod. e rodar app.
FROM node:22-alpine3.18

WORKDIR /app

COPY package.json pnpm-lock.yaml .env ./
RUN npm install --prod

COPY --from=build /app/build ./build

EXPOSE 3003

CMD ["npm", "start"]
