FROM node:22-alpine3.18

COPY src /src/src
COPY package.json /src
COPY pnpm-lock.yaml /src

WORKDIR /src
RUN pnpm install

COPY --from=build /src/app.js /src/app.js 

WORKDIR /src

EXPOSE 8080

CMD ["node", "./build/app.js"]